name: Docker Image Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build and Upload to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      # - name: Get Version
      #   if: startsWith(github.ref, 'refs/tags/v')
      #   id: vars
      #   run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: Build and push (release)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag saching12/ubuntu-images:galactic-dev \
            -f Dockerfile_galactic \
            --output "type=image,push=true" .

          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag saching12/ubuntu-images:humble-dev \
            -f Dockerfile_humble \
            --output "type=image,push=true" .

          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag saching12/ubuntu-images:noetic-dev \
            -f Dockerfile_noetic \
            --output "type=image,push=true" .

          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag saching12/ubuntu-images:kimera-dev \
            -f Dockerfile_kimera_dev \
            --output "type=image,push=true" .
